baseURL = 'https://abelvanoosterwijk.com'
languageCode = 'nl-NL'
defaultContentLanguage = "nl"
defaultContentLang = "nl"
canonifyURLs = true
disablekinds = ['section', 'taxonomy']

title = 'Abel van Oosterwijk'
[params]
description = 'Publicatielijst van Abel'
email = 'contact@abelvanoosterwijk.com'
