backend:
  name: github
  repo: yochem/abel # TODO
  branch: main
media_folder: static/media
public_folder: /media
# site_url: https://abelvanoosterwijk.com # TODO
collections:
  - name: publicaties
    label: Publicaties
    label_singular: Publicatie
    folder: content/publicaties
    create: true
    editor:
      preview: false
    fields:
      - label: Paginanaam
        name: slug
        widget: string
        pattern: ['[a-z0-9_-]+', 'Toegestaan: a-z, 0-9, _ en -']
        hint: |
          De paginanaam in de URL:
          abelvanoosterwijk.com/publicaties/{{ paginanaam }}/.
      - label: Title
        name: title
        widget: string
        hint: Je kan `*italics*` en `**bold**` gebruiken.
      - label: Subtitle
        name: summary
        widget: string
        required: false
        hint: Je kan `*italics*` en `**bold**` gebruiken.
      - label: Publish Date
        name: date
        widget: datetime
      - label: Draft
        name: draft
        widget: boolean
        default: false
        hint: Drafts zijn niet zichtbaar op de site.
      - label: Article URL
        name: link
        widget: string
        required: false
        hint: |
          Link naar het artikel op een andere website. Laat leeg voor een
          artikel op deze website.
      - label: Article Text
        name: body
        widget: markdown
        required: false
        hint: De tekst voor een artikel op deze website.
